import { readFile, writeFile } from "node:fs/promises";
import { normalizeUrlFields } from "./url-policy.mjs";

const SOURCE_PATH = new URL("../data/data.json", import.meta.url);
const OUTPUT_PATH = new URL("../data.js", import.meta.url);
const DATASET_ORDER = ["included", "review", "global"];

function normalizeDataset(data) {
  const next = {
    generated_at: data.generated_at,
    datasets: {},
  };
  const issues = [];

  for (const key of DATASET_ORDER) {
    const bucket = data.datasets?.[key];

    if (!bucket) {
      continue;
    }

    next.datasets[key] = {
      ...bucket,
      records: (bucket.records || []).map((record, index) => {
        const id = record.error_id || record.candidate_id || `${key}[${index}]`;
        const normalized = normalizeUrlFields(record, `${key}.${id}`);
        issues.push(...normalized.issues);
        return normalized.record;
      }),
    };
  }

  for (const [key, bucket] of Object.entries(data.datasets || {})) {
    if (next.datasets[key]) {
      continue;
    }

    next.datasets[key] = {
      ...bucket,
      records: (bucket.records || []).map((record, index) => {
        const id = record.error_id || record.candidate_id || `${key}[${index}]`;
        const normalized = normalizeUrlFields(record, `${key}.${id}`);
        issues.push(...normalized.issues);
        return normalized.record;
      }),
    };
  }

  return { data: next, issues };
}

function buildBrowserBundle(data) {
  const json = JSON.stringify(data, null, 2);
  return [
    "// Generated from data/data.json by scripts/build-data.mjs",
    "// Do not edit this file by hand.",
    `window.AIEL_DATA = ${json};`,
    "",
  ].join("\n");
}

const sourceText = await readFile(SOURCE_PATH, "utf8");
const sourceData = JSON.parse(sourceText);
const normalized = normalizeDataset(sourceData);

if (normalized.issues.length) {
  console.error("Data build failed:\n");
  for (const issue of normalized.issues) {
    console.error(`- ${issue}`);
  }
  process.exit(1);
}

await writeFile(SOURCE_PATH, `${JSON.stringify(normalized.data, null, 2)}\n`, "utf8");
await writeFile(OUTPUT_PATH, buildBrowserBundle(normalized.data), "utf8");

console.log(`Built ${OUTPUT_PATH.pathname.split("/").pop()} from ${SOURCE_PATH.pathname.split("/").pop()}.`);
