import { readFile, writeFile } from "node:fs/promises";

const SOURCE_PATH = new URL("../data/data.json", import.meta.url);
const OUTPUT_PATH = new URL("../data.js", import.meta.url);
const DATASET_ORDER = ["included", "review", "global"];
const URL_FIELDS = ["public_record_link", "secondary_source_links", "best_available_sources"];

function normalizeUrl(value) {
  try {
    const url = new URL(value);
    if (url.protocol === "http:") {
      url.protocol = "https:";
    }
    if (url.hostname.toLowerCase().startsWith("www.")) {
      url.hostname = url.hostname.slice(4);
    }
    return url.toString();
  } catch {
    return value;
  }
}

function normalizeUrlList(value) {
  return String(value || "")
    .split(";")
    .map((item) => item.trim())
    .filter(Boolean)
    .map(normalizeUrl)
    .join("; ");
}

function normalizeRecord(record) {
  const next = { ...record };

  for (const field of URL_FIELDS) {
    if (!next[field]) {
      continue;
    }

    if (field === "public_record_link") {
      next[field] = normalizeUrl(String(next[field]).trim());
      continue;
    }

    next[field] = normalizeUrlList(next[field]);
  }

  return next;
}

function normalizeDataset(data) {
  const next = {
    generated_at: data.generated_at,
    datasets: {},
  };

  for (const key of DATASET_ORDER) {
    const bucket = data.datasets?.[key];

    if (!bucket) {
      continue;
    }

    next.datasets[key] = {
      ...bucket,
      records: (bucket.records || []).map(normalizeRecord),
    };
  }

  for (const [key, bucket] of Object.entries(data.datasets || {})) {
    if (next.datasets[key]) {
      continue;
    }

    next.datasets[key] = {
      ...bucket,
      records: (bucket.records || []).map(normalizeRecord),
    };
  }

  return next;
}

function buildBrowserBundle(data) {
  const json = JSON.stringify(data, null, 2);
  return [
    "// Generated from data/data.json by scripts/build-data.mjs",
    "// Do not edit this file by hand.",
    `window.AIEL_DATA = ${json};`,
    "",
  ].join("\n");
}

const sourceText = await readFile(SOURCE_PATH, "utf8");
const sourceData = JSON.parse(sourceText);
const normalizedData = normalizeDataset(sourceData);

await writeFile(SOURCE_PATH, `${JSON.stringify(normalizedData, null, 2)}\n`, "utf8");
await writeFile(OUTPUT_PATH, buildBrowserBundle(normalizedData), "utf8");

console.log(`Built ${OUTPUT_PATH.pathname.split("/").pop()} from ${SOURCE_PATH.pathname.split("/").pop()}.`);

